- platform: broadlink
  host: 10.10.1.210
  mac: '34:EA:34:43:08:41'
  timeout: 15
  switches:
    # Will work on most Phillips TVs:
    tv_phillips:
      friendly_name: "Phillips Tv"
      command_on: 'JgAcAB0dHB44HhweGx4cHR06HB0cHhwdHB8bHhwADQUAAAAAAAAAAAAAAAA='
      command_off: 'JgAaABweOR4bHhwdHB4dHRw6HhsdHR0dOTocAA0FAAAAAAAAAAAAAAAAAAA='
    tv_nc:
      friendly_name: "Dekoder NC+"
      command_on: 'JgBYAAABKpUTOBM3EzgSEhMSExITEhI4ExITNxM4EjgTNxMSFTYSEhUQEzgSEhMSEzgSEhUQExITNxMSEzgSOBMSEzcTOBI4EwAFBwABKksTAAx3AAEsSRMADQU='
      command_off: 'JgBYAAABKpUTOBM3EzgSEhMSExITEhI4ExITNxM4EjgTNxMSFTYSEhUQEzgSEhMSEzgSEhUQExITNxMSEzgSOBMSEzcTOBI4EwAFBwABKksTAAx3AAEsSRMADQU='
#    soundbar:
#      friendly_name: "Soundbar Thomson"
#      command_on: 'JgBYAAABNJQWNRY1FBITExMTExMTExMTExMTEhQ3FjUWNRQ3FDcWNhMTExIUEhM4FBITOBM4ExMTOBM4EzgTExM4ExMTExM4FAAFHgABNUgWAAxaAAE1SBYADQU='
#      command_off: 'JgBYAAABNJQWNRY1FBITExMTExMTExMTExMTEhQ3FjUWNRQ3FDcWNhMTExIUEhM4FBITOBM4ExMTOBM4EzgTExM4ExMTExM4FAAFHgABNUgWAAxaAAE1SBYADQU='
    amp_onkyo:
      friendly_name: "Wzmacniacz Onkyo"
      command_on: 'JgBYAAABJ5IVEBU1FBAVEBU1FBEUNRU1FDUVEBU1FDUVEBU1FDUVEBUQFBEUNRUQFRAUERQQFRAVNRQ1FRAVNRQ1FTUUNRU1FQAE9QABKEgVAAxJAAEoSBUADQU='
      command_off: 'JgBYAAABKJEVEBU1FBEUEBU1FRAUNRU1FRAUERQ1FTUUEBU1FTUUEBU1FTUUNRUQFRAUERQ1FRAVEBQRFBAVNRQ1FTUVEBQ1FQAFGgABKEkUAAxJAAEoSRQADQU='
    fan_remote:
      friendly_name: "Wentylator"
      command_on: 'JgDQACsNKwwPKCsNKw0PKA8oECcQKA8oKw0PAAEGKw0qDQ8oKw0rDA8oECgPKBAoDygrDQ8AAQUsDCsNDygrDSoNDygQJxAoDygQKCsNDwABBSwMKw0PKCsMKw0PKA8oECgPKBAoKwwPAAEGKw0rDA8oLAwrDQ8oDygQJxAoECcsDA8AAQYrDSoNDygrDSsMDygQKA8oECgPKCsNDwABBisNKg0PKCsNKwwPKBAoDygQJxAoKw0PAAEFLAwrDQ8oKw0qDQ8oECcQKA8oECgrDQ8ADQUAAAAAAAAAAA=='
      command_off: 'JgDCACsNKwwPKCwMKw0PJxAoECcQKA8oECgr6isNKg0PKCsNKwwQJxAoDygQKA8oECcs6SwMKw0PKCsNKwwPKBAoDygQJxAoDygs6SwMKw0PKCsMKw0PKBAnECgPKBAoDygr6isNKwwQJywMKw0PKA8oECcQKBAnECgr6isNKwwPKCwMKwwQJxAoECcQKA8oECgr6isNKg0PKCsNKwwPKBAoDygQJxAoECcs6SwMKw0PKCsNKwwPKBAnECgQJxAoDygQAA0FAAAAAAAA'
      ### rotate: 'JgA4ASsNKg0PKCsNKwwPKBAoKw0PKA8oECgPAAEGKw0qDQ8oKw0rDA8oECgrDQ8nECgQKA8AAQUsDCsNDygrDSoNDygQJywMDygQKA8oEAABBSwMKw0PKCsMKw0PKA8oKw0PKBAoDygQAAEFKw0rDBAnLAwrDQ8oDygrDQ8oECcQKA8AAQYrDSsMDygrDSsMECcQKCsNDygQJxAoDwABBisNKg0PKCsNKg0PKBAoKw0PKA8oDygQAAEFLAwqDg8oKg4pDg4pDygrDQ4pECgPKBAAAQUqDioODikpDikPDSoOKQ8pDikOKQ8pDgABBykPKA8OKSkPKQ8NKg0qDikPKQ4pDykOAAEHKQ8oDw0qKQ8pDwwqDioOKQ8pDikPKQ4AAQcpDygPDSopDygPDSoPKQ4pDikPKQ4pDwANBQ=='

- platform: broadlink
  host: 10.10.1.212
  mac: '78:0F:77:47:9D:A8'
  timeout: 15
  switches:
    soundbar:
      friendly_name: "Soundbar Thomson"
      command_on: 'JgBYAAABNJQWNRY1FBITExMTExMTExMTExMTEhQ3FjUWNRQ3FDcWNhMTExIUEhM4FBITOBM4ExMTOBM4EzgTExM4ExMTExM4FAAFHgABNUgWAAxaAAE1SBYADQU='
      command_off: 'JgBYAAABNJQWNRY1FBITExMTExMTExMTExMTEhQ3FjUWNRQ3FDcWNhMTExIUEhM4FBITOBM4ExMTOBM4EzgTExM4ExMTExM4FAAFHgABNUgWAAxaAAE1SBYADQU='